### ISSUE TITLE
Evaluation for Python

### ISSUE THREAD

**Issue by jchristgit** [SpecialKids/HackBoat#7]
Add Code Evaluation for Python.

- [ ] Add `!eval python` for authorized Users

- [ ] Add `!eval python` for non-authorized Users

For the latter, restriction of input might be necessary. Possible options:

- import some "safe" modules, e.g. numpy

- restrict further imports and other built-in functions that could cause harm

**Comment by wubbalubbadubdubonline** [comment]
```py
bl = ['**', '__', 'lambda']

for item in bl:
    if item in user_input:
        return

eval(user_input, {'__builtins__': {}})
