### ISSUE TITLE
Evaluation for Elixir

### ISSUE THREAD

**Issue by jchristgit** [SpecialKids/HackBoat#9]
Add Evaluation for Elixir.

- [X] Add `!eval elixir` command for authorized Users

- [ ] Add `!eval elixir` for non-authorized Users

options for "safely" evaluating code by non-authorized Users?

**Comment by cronokirby** [comment]
Gonna be hard to sandbox it.
We have 2 solutions:

1. spoof an existing playground
2. sandbox ourselves the way those existing playgrounds have
